// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjwiimmnkxstmnxgyfrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qd2lpbW1ua3hzdG1ueGd5ZnJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Mjg0NjgsImV4cCI6MjA2MjAwNDQ2OH0.PO5FlxabC1_mr2A_gFpgwSoj9h5a9LU4lBTQCCQlGho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);